git clone git@github.com:JackGxd/imagesbuild.git mkdir -vp imagesbuild/sig-storage/skywalking imagesbuild/sig-storage/skywalking/Dockerfile  <<'EOF'
FROM apache/skywalking-oap-server:10.0.1
LABEL MAINTAINER=master@gxd BUILDTYPE=Aliyun
EOFgit add . && git commit -m "skywalking" && git push
